import React from "react";
const image = "https://cdn3d.iconscout.com/3d/premium/thumb/user-3711707-3105429.png?f=webp";

const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "NAME", uid: "name", sortable: true},
  {name: "AGE", uid: "age", sortable: true},
  {name: "ROLE", uid: "role", sortable: true},
  {name: "TEAM", uid: "team"},
  {name: "EMAIL", uid: "email"},
  {name: "STATUS", uid: "status", sortable: true},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Paused", uid: "paused"},
  {name: "Vacation", uid: "vacation"},
];

const users = [
  {
    id: 1,
    name: "طالب 1",
    role: "06589654796",
    team: "تلميذ سنة الاولى ثانوي",
    status: "active",
    age: "29",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "طالب 2",
    role: "064879461",
    team: "تلميذ سنة الاولى ثانوي",
    status: "paused",
    age: "25",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "طالب 3",
    role: "06184967",
    team: "تلميذ سنة الثانية متوسط ",
    status: "active",
    age: "22",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "طالب 4",
    role: "تلميذ سنة الاولى ثانوي.",
    team: "Marketing",
    status: "vacation",
    age: "28",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "طالب 5",
    role: "تلميذ سنة الاولى ثانوي",
    team: "Sales",
    status: "active",
    age: "24",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "طالب 6",
    role: "تلميذ خارج عن التغطية سنة الاولى ثانوي",
    team: "Management",
    age: "29",
    email: "brian.kim@example.com",
    status: "Active",
  },
  {
    id: 7,
    name: "خليفة طارق",
    role: "تلميذ سنة الاولى ثانوي",
    team: "Design",
    status: "paused",
    age: "27",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "سماج وخداخر",
    role: "غير معروف",
    team: "غير معروف",
    status: "active",
    age: "31",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "BLIDI INFORMATIQUE 2024",
    role: "رقم غير معروف",
    team: "Finance",
    status: "vacaimage",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "بن مستاري صفيان",
    role: "Ops Manager",
    team: "Operations",
    status: "active",
    age: "35",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "يوسف",
    role: "Jr. Dev",
    team: "Development",
    status: "active",
    age: "22",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "داعيزة",
    role: "P. Manager",
    team: "Product",
    status: "paused",
    age: "28",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "شارف نقطعك",
    role: "S. Manager",
    team: "Security",
    status: "active",
    age: "37",
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    name: "اوريعة 2023",
    role: "M. Specialist",
    team: "Marketing",
    status: "active",
    age: "30",
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    name: "لولاوي",
    role: "IT Specialist",
    team: "I. Technology",
    status: "paused",
    age: "31",
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    name: "كريم بالونة",
    role: "Manager",
    team: "Sales",
    status: "active",
    age: "29",
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    name: "باندا محمد",
    role: "Data Analyst",
    team: "Analysis",
    status: "active",
    age: "28",
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    name: "بلحول المريض",
    role: "QA Analyst",
    team: "Testing",
    status: "active",
    age: "27",
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    name: "فرانكلين",
    role: "Administrator",
    team: "Information Technology",
    status: "paused",
    age: "32",
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    name: "سليم الاكول",
    role: "Coordinator",
    team: "Operations",
    status: "active",
    age: "26",
    email: "mia.robinson@example.com",
  },
];

export {columns, users, statusOptions};
