import { Katibeh } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
const ket = Katibeh(
  {
  subsets: ['arabic'],
  weight: "400"
  })

export const metadata = {
  title: 'برنامج ادارة أكادمية التحدي الاصدار 1.0.0',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }){
  return (
    <html lang="ar" className={`dark bg-black text-white ${ket.className}`}>
      <body className={`${ket.className} purple-dark text-foreground bg-background`}>
        <Providers className={`${ket.className}`}>
         {children}
        </Providers>
      </body>
    </html>
  )
}
